sudo: false

language: python

before_install:
  - sudo apt-get install -y rpm

install: pip install tox

matrix:
  include:
  - python: "2.7"
    env: TOX_ENV=cov-travis DEPLOY=1
  - python: "3.6"
    env: TOX_ENV=py36

script: tox -e $TOX_ENV

deploy:
  provider: pypi
  user: content-delivery-release-bot
  password:
    secure: NHG/gima8D2grSQMZpn+Yllke53pa304Pw7c5gwCrdGOmWBxcZhviMLNTJTXi0QDMf9KJwS1hsmsxMFqiM9ui2bUO7VBMPR+n8GSvy0ax0viNTXXXNhzTVW9UfPs1dRCmrGrNWcKl4SJ4IrvWF882jkZWTjfnWCzBdDl5sV7VAi5ydPbv9FGjMZ/8WCVMthq9A0hXnqKNbwEDRR9urhS56AS8alT6mWvLt7IJfeTupMB8Uv0jR0b36yftSOZ97BcFdQaEWVhXUNRL6PRwKER5mLij0MQUhDeyA3zJIF2NhimEWjN3CLJlPhJv6NjfP6AVfOy4Gbj7N+gyCFJ/djJjpltZ4d8/dlZgcJuQSxmAxXRhXwX80KG8TvExmvSzMJviR0zc6RqBP5YIvP+RBFhtu6DwEotsE/KIF0CQ7PsRyYsQD/5/Lt+F+otxN4QXIUP+Z47IwK3xknThKtCclAs4r/14xsHqKwq2lSeEJJ2MIDpwCgzqCyNuckYTgIiWu9b6gMNgj1TT2Lhn/cmwCh9Y2lX0qy0y5WlJEKIZE9P2odaJCPsX7/A9LIY2HN9vVYb+uqx2TLeyIJg3e9V7T8qt61y0TnMxhLYQOmsi8Knro2ZW+X2+2kKpXRJMoAvOD6UKgnpWsT48yg0191CGDKjOWuBKLH06qr+MZJ0X3SBwxg=
  on:
    tags: true
    condition: $DEPLOY = 1
  skip_existing: true
